# Generated by Django 4.1 on 2022-08-06 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action', models.CharField(choices=[('T', 'Tuning'), ('R', 'Re-heading'), ('C', 'Cleaning')], default='T', max_length=1)),
                ('drum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.drum')),
            ],
        ),
    ]
