# Generated by Django 4.1 on 2022-08-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(verbose_name='Maintenance date'),
        ),
    ]
